# Site settings
title: Frankie Mercado
email: f@frankiemercado.com
description: > # this means to ignore newlines until "baseurl:"
  Frankie Mercado's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frankiemercado.com" # the base hostname & protocol for your site
twitter_username: IHTFY
github_username:  IHTFY

# Build settings
markdown: kramdown
highlighter: rouge